### ISSUE TITLE
Create a new release for Milestone 3

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#63]
TODOs:
- [x] Create a new tag `v2.0.0`
- [x] Bump version in `pyproject.toml`
- [x] Include changes in `CHANGELOG.md`

**Comment by shawnhu444** [comment]
agreed on the changes
