### ISSUE TITLE
Create a release for Milestone 4

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/VisuMorph#94]
- [x] Create a new tag v3.0.0
- [x] Bump version in pyproject.toml
- [x] Include changes in CHANGELOG.md (Should be automatic?)
